#!/bin/sh
# Copyright (C) 2012 Luka Perkov <freecwmp@lukaperkov.net>

get_device_users() {
local parameter="$1"
case "$parameter" in
	Device.Users.UserNumberOfEntries)
	local val=`wc -l /etc/passwd | awk '{ print $1 }'`
	freecwmp_output "$parameter" "$val"
	return
	;;
esac

local rc
local num

# TODO: Device.Users.User.{i}.Alias (alias support does not exist)

freecwmp_parse_formated_parameter "$parameter" "Device Users User {i} Enable" "rc" "num"
if [ $rc -eq 0 ]; then
	# TODO: this is very system dependent, for now just look at users shell
	local sed_cmd=`echo -n \'$num; echo p\'`
	local val=`eval sed -n $sed_cmd /etc/passwd | grep -v '/bin/false' | wc -l`
	freecwmp_output "$parameter" "$val"
	return
fi

freecwmp_parse_formated_parameter "$parameter" "Device Users User {i} RemoteAccessCapable" "rc" "num"
if [ $rc -eq 0 ]; then
	# TODO: this is very system dependent, for now just look at users shell
	local sed_cmd=`echo -n \'$num; echo p\'`
	local val=`eval sed -n $sed_cmd /etc/passwd | grep -v '/bin/false' | wc -l`
	freecwmp_output "$parameter" "$val"
	return
fi

freecwmp_parse_formated_parameter "$parameter" "Device Users User {i} Username" "rc" "num"
if [ $rc -eq 0 ]; then
	local sed_cmd=`echo -n \'$num; echo p\'`
	local val=`eval sed -n $sed_cmd /etc/passwd | awk -F ':' '{ print $1 }'`
	freecwmp_output "$parameter" "$val"
	return
fi

freecwmp_parse_formated_parameter "$parameter" "Device Users User {i} Password" "rc" "num"
if [ $rc -eq 0 ]; then
	local sed_cmd=`echo -n \'$num; echo p\'`
	# if we *really* wanted to get the password we could do it like this
	#   local val=`eval sed -n $sed_cmd /etc/shadow | awk -F ':' '{ print $2 }'`
	#   freecwmp_output "$parameter" "$val"
	freecwmp_output "$parameter" ""
	return
fi

freecwmp_parse_formated_parameter "$parameter" "Device Users User {i} Language" "rc" "num"
if [ $rc -eq 0 ]; then
	freecwmp_output "$parameter" ""
	return
fi
}
